#!/bin/bash

PWD=`pwd`
echo "Auditing $PWD" > audit.txt

tree -h  >> audit.txt

echo '# files submitted' >> audit.txt
find . -type f | wc -l >> audit.txt
echo 'Scripts (target 42):' >> audit.txt
find . -type f -name '*.m' | wc -l >> audit.txt
echo 'Simulink models (target 7):' >> audit.txt
find . -type f -name '*.slx' | wc -l >> audit.txt

echo "Diffs in diffs.txt" >> audit.txt
diff ../model_audit.txt audit.txt > diffs.txt
